### PR TITLE
Update LiveMigration bandwidth limit to match Validate-DCB

### PR DESCRIPTION
**Pull request by JTF195**
Validate-DCB expects the LiveMigration bandwidth limit to be 60% of the configured SMB traffic class bandwidth limit for a single adapter in the vSwitch (it checks whichever one is last in adapters[i], but it's better to limit it to the slowest one)

### CODE REVIEW

**Comment by jaromirk** [comment]
I know. but I don't thin 60% is OK as I think less than 50 percent should be configured. if one adapter will fail, then LM can eat all bandwidth. but it's up to you. can be specified in config - see validate dcb scenario https://github.com/Microsoft/WSLab/tree/master/Scenarios/S2D%20and%20Validate-DCB

**Comment by JTF195** [comment]
The SMB bandwidth is set to 60%, and then the LiveMigration bandwidth limit is set to 60% *of that*, which ends up being only 36%

I also changed it to use the bandwidth of the slowest single adapter in the vSwitch rather than the sum of all the adapters in the system.

**Comment by jaromirk** [comment]
ah, got it! will review it today. thank you very much for contribution!

**Comment by jaromirk** [comment]
Hello, sorry for delay. I validated with colleague and he confirmed what I thought before. if you set BandwidthPercentage, it's not hard limit. Therefore your calculation does not apply. If you create 60%, it does not mean that SMB traffic can use just 60%.

•	There is uniform management of all types of traffic on the link, both congestion-managed traffic and standard Ethernet traffic.
•	When a priority group does not use all of its allocated bandwidth, other priority groups on the link can use that bandwidth as needed. 
•	When a priority in a priority group does not use all of its allocated bandwidth, other priorities in the group can use that bandwidth. 
•	The result is better bandwidth utilization, because priorities that consist of bursty traffic can share bandwidth during periods of low traffic transmission instead of consuming their entire bandwidth allocation when traffic loads are light.
•	You can assign traffic types with different service needs to different priorities so that each traffic type receives appropriate treatment.
•	Strict priority traffic retains its allocated bandwidth.

**Pull request closed without merging**
